version: '3'

vars:
  PATH: "${KREW_ROOT:-$HOME/.krew}/bin:~/.arkade/bin:$PATH"

tasks:
  install-apt-fast:
    cmds:
    - |
      apt-get update && apt-get install -y -q sudo gnupg age
      /bin/bash -c "$(curl -sL https://git.io/vokNn)"
      echo debconf apt-fast/maxdownloads string 16 | debconf-set-selections
      echo debconf apt-fast/dlflag boolean true | debconf-set-selections
      echo debconf apt-fast/aptmanager string apt-get | debconf-set-selections
      echo 'MIRRORS=( 'http://deb.debian.org/debian','http://ftp.debian.org/debian, http://ftp2.de.debian.org/debian, http://ftp.de.debian.org/debian, ftp://ftp.uni-kl.de/debian' )' >> /etc/apt-fast.conf

  install-utils:
    deps:
    - install-apt-fast
    cmds:
    - apt-fast install -y -q direnv curl wget aria2 axel file tree ncdu neofetch htop dstat iotop unzip git apt-transport-https ca-certificates

  oh-my-bash:
    deps:
    - install-utils
    cmds:
    - bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" --unattended
    silent: false

  install-upx:
    dir: /tmp
    run: once
    cmds:
    - |
      wget -q https://github.com/upx/upx/releases/download/v$UPX_VERSION/upx-v$4.2.1-amd64_linux.tar.xz
      tar xf upx-4.2.1-amd64_linux.tar.xz
      mv upx-4.2.1-amd64_linux/upx /usr/local/bin/
      chmod +x /usr/local/bin/upx
      rm -fr upx-4.2.1-amd64*

  install-dingtalk:
    dir: /tmp
    cmds:
    - |
      wget -q https://github.com/CatchZeng/dingtalk/releases/download/v1.5.0/dingtalk-linux-amd64.zip
      unzip -d /usr/local/bin dingtalk-linux-amd64.zip
      rm -f dingtalk-linux-amd64.zip
      chmod +x /usr/local/bin/dingtalk

  install-arkade:
    run: once
    deps:
    - install-upx
    cmds:
    - aria2c -d /usr/local/bin https://github.com/alexellis/arkade/releases/download/0.10.17/arkade
    - chmod +x /usr/local/bin/arkade
    - upx /usr/local/bin/arkade

  arkade-install-utils:
    deps:
    - install-arkade
    cmds:
    - arkade get fzf gh jq sops lazygit mc mkcert packer terraform
    - arkade get gomplate hadolint k9s nerdctl cr dive crane
    - mv ~/.arkade/bin/* /usr/local/bin/

  arkade-install-kubectl:
    dir: /tmp
    deps:
    - install-arkade
    - bashrc-kubectl-alias
    cmds:
    - arkade get kubectl@v1.23.3 kustomize kubecm
    - mv ~/.arkade/bin/kubectl /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl
    - |
      (
      set -x; cd "$(mktemp -d)" &&
      OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
      ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
      KREW="krew-${OS}_${ARCH}" &&
      curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
      tar zxvf "${KREW}.tar.gz" &&
      ./"${KREW}" install krew
      )
    - echo 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:~/.arkade/bin:$PATH"' >> ~/.bashrc
    - export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"; /usr/local/bin/kubectl krew install stern ice df-pv ktop view-cert viewnode ssh-jump sick-pods restart resource-capacity prune-unused datree example get-all gopass htpasswd images kc ktop konfig neat nsenter popeye
    - aria2c https://github.com/particledecay/kconf/releases/download/v2.0.0/kconf-linux-x86_64-2.0.0.tar.gz

  arkade-install-helmfile:
    deps:
    - arkade-install-kubectl
    cmds:
    - arkade get helm helmfile popeye stern flux kail; mv /root/.arkade/bin/* /usr/local/bin; chmod +x /usr/local/bin/*
    - helm plugin install https://github.com/databus23/helm-diff
    - helm plugin install https://github.com/chartmuseum/helm-push
    - |
      aria2c https://github.com/nikhilsbhat/helm-images/releases/download/v0.1.0/helm-images_0.1.0_Linux_x86_64.tar.gz
      mkdir -p  /root/.local/share/helm/plugins/helm-images
      tar -xvf helm-images_0.1.0_Linux_x86_64.tar.gz -C /root/.local/share/helm/plugins/helm-images
      rm -rf helm-images*

  helm-plugin-install:
    dir: /tmp
    cmds:
    - helm plugin install https://github.com/hypnoglow/helm-s3.git

  apt-install:
    deps:
    - install-apt-fast
    cmds:
    - apt-fast install -y dropbear neovim exa

  github-install:
    cmds:
    - task: github-install-xh
    - task: github-install-starship
    - task: github-install-skopeo
    #- dust, btop, ctop, lazydocker
    - wget -O /usr/local/bin/yj https://github.com/sclevine/yj/releases/download/v5.1.0/yj-linux-amd64

  github-install-skopeo:
    cmds:
    #- dust, btop, ctop, lazydocker
    - wget -O /usr/local/bin/skopeo https://github.com/lework/skopeo-binary/releases/download/v1.13.3/skopeo-linux-amd64

  github-install-kubie:
    cmds:
    - wget -O /usr/local/bin/kubie https://github.com/sbstp/kubie/releases/download/v0.22.0/kubie-linux-amd64

  github-install-starship:
    dir: /tmp
    cmds:
    - |
      wget https://github.com/starship/starship/releases/download/v1.16.0/starship-x86_64-unknown-linux-musl.tar.gz
      tar xf starship-x86_64-unknown-linux-musl.tar.gz
      mv starship /usr/local/bin
      echo 'eval "$(starship init bash)"' >> ~/.bashrc
      rm -f starship-x86_64-unknown-linux-musl.tar.gz

  apt-install-nfpm:
    dir: /tmp
    cmds:
    - apt-get install -y ruby-dev build-essential
    - gem i fpm -f
    - wget https://github.com/goreleaser/nfpm/releases/download/v2.34.0/nfpm_2.34.0_amd64.deb; dpkg -i nfpm_2.34.0_amd64.deb; rm -f dpkg -i nfpm_2.34.0_amd64.deb

  brew-install:
    cmds:
    - brew install asdf dust fzf autojump zoxide
    - echo '. "$HOME/.asdf/asdf.sh" >> ~/.bashrc
    - echo '. "$HOME/.asdf/completions/asdf.bash"' >> ~/.bashrc

  bashrc-complete-alias:
    cmds:
    - wget -O ~/.complete_alias https://raw.githubusercontent.com/cykerway/complete-alias/master/complete_alias
    - echo "#--- complete_alias ---#" >> ~/.bashrc
    - echo 'export COMPAL_AUTO_UNMASK=1' >> ~/.bashrc

  bashrc-kubectl-alias:
    cmds:
    - wget -O ~/.kubectl_aliases https://raw.githubusercontent.com/ahmetb/kubectl-aliases/master/.kubectl_aliases
    - echo '[ -f ~/.kubectl_aliases ] && source ~/.kubectl_aliases' >> ~/.bashrc

  github-install-xh:
    dir: /tmp
    cmds:
    - |
      wget https://github.com/ducaale/xh/releases/download/v0.20.1/xh-v0.20.1-x86_64-unknown-linux-musl.tar.gz
      tar xf xh-v0.20.1-x86_64-unknown-linux-musl.tar.gz
      mv xh-v0.20.1-x86_64-unknown-linux-musl/xh /usr/local/bin/
      rm -f xh-v0.20.1-x86_64-unknown-linux-musl.tar.gz

  upx-compress:
    cmds:
    - /usr/local/bin/upx /usr/local/bin/* || true
    - /usr/local/bin/upx ~/.arkade/bin/* || true

  clean-tmp:
    cmds:
    - rm -rf /tmp/*

  build:
    cmds:
    - task: oh-my-bash
    - task: bashrc-complete-alias
    - task: install-dingtalk
    - task: apt-install
    - task: arkade-install-utils
    - task: arkade-install-helmfile
    #- task: brew-install
    - task: github-install
    #- task: apt-install-fpm
    - task: upx-compress
    - chmod +x /usr/local/bin/*
    - task: clean-tmp

  default:
    cmds:
    - task: build
