version: '3'

tasks:
  install-apt-fast:
    cmds:
    - |
      apt-get update && apt-get install -y sudo gnupg
      /bin/bash -c "$(curl -sL https://git.io/vokNn)"
      echo debconf apt-fast/maxdownloads string 16 | debconf-set-selections
      echo debconf apt-fast/dlflag boolean true | debconf-set-selections
      echo debconf apt-fast/aptmanager string apt-get | debconf-set-selections
      echo 'MIRRORS=( 'http://deb.debian.org/debian','http://ftp.debian.org/debian, http://ftp2.de.debian.org/debian, http://ftp.de.debian.org/debian, ftp://ftp.uni-kl.de/debian' )' >> /etc/apt-fast.conf
  
  install-utils:
    deps:
    - install-apt-fast
    cmds:
    - apt-fast install -y direnv curl wget aria2 axel file tree ncdu neofetch htop dstat iotop unzip git
    
  oh-my-bash:
    deps:
    - install-utils
    cmds:
    - bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" --unattended
    silent: false
    
  install-upx:
    dir: /tmp
    cmds:
    - |
      wget https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-amd64_linux.tar.xz
      tar xf upx-4.2.1-amd64_linux.tar.xz
      mv upx-4.2.1-amd64_linux/upx /usr/local/bin/ && chmod +x /usr/local/bin/upx
      
  install-dingtalk:
    deps:
    - install-upx
    dir: /tmp
    cmds:
    - |
      wget https://github.com/CatchZeng/dingtalk/releases/download/v1.5.0/dingtalk-linux-amd64.zip
      unzip -d /usr/local/bin dingtalk-linux-amd64.zip
      rm -f dingtalk-linux-amd64.zip
      chmod +x /usr/local/bin/dingtalk
      upx /usr/local/bin/dingtalk

  install-linuxbrew:
    cmds:
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    
  install-arkade:
    run: once
    cmds:
    - curl -sLS https://get.arkade.dev | sh
    
  arkade-install-utils:
    deps:
    - install-arkade
    cmds:
    - arkade get fzf gh jq sops lazygit mc mkcert packer terraform 
    - arkade get gomplate hadolint k9s nerdctl cr dive crane 

  arkade-install-kubectl:
    deps:
    - install-arkade
    - bashrc-kubectl-alias
    cmds:
    - arkade get kubectl@v1.23.3 kustomize kubecm
    - |
      (
      set -x; cd "$(mktemp -d)" &&
      OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
      ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
      KREW="krew-${OS}_${ARCH}" &&
      curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
      tar zxvf "${KREW}.tar.gz" &&
      ./"${KREW}" install krew
      )
    - echo 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"' >> ~/.bashrc
    - kubectl krew install ice df-pv ktop
    
  arkade-install-helmfile:
    deps:
    - arkade-install-kubectl
    cmds:
    - arkade get helm helmfile popeye stern flux kail
    - helm plugin install https://github.com/databus23/helm-diff
    - helm plugin install https://github.com/chartmuseum/helm-push
    - helm plugin install https://github.com/nikhilsbhat/helm-images
    - helm plugin install https://github.com/hypnoglow/helm-s3.git

  apt-install:
    deps:
    - install-apt-fast
    cmds:
    - apt-fast install -y dropbear neovim exa
    
  #github-install:
  # cmds:
  #  - dust, btop, ctop, lazydocker
  
  github-install-kubie:
    cmds:
    - wget -O /usr/local/bin/kubie https://github.com/sbstp/kubie/releases/download/v0.22.0/kubie-linux-amd64

  github-install-starship:
    cmds:
    - curl -sS https://starship.rs/install.sh | sh
    - echo 'eval "$(starship init bash)"' >> ~/.bashrc

  apt-install-fpm:
    cmds:
    - apt-get install -y ruby-dev build-essential
    - gem i fpm -f
    
  brew-install:
    deps:
    - install-linuxbrew
    cmds:
    - brew install asdf age dust fzf autojump zoxide nfpm yj
    - echo '. "$HOME/.asdf/asdf.sh" >> ~/.bashrc
    - echo '. "$HOME/.asdf/completions/asdf.bash"' >> ~/.bashrc

  bashrc-complete-alias:
    cmds:
    - wget -O ~/.complete_alias https://raw.githubusercontent.com/cykerway/complete-alias/master/complete_alias
    - echo "#--- complete_alias ---#" >> ~/.bashrc
    - echo 'export COMPAL_AUTO_UNMASK=1' >> ~/.bashrc

  bashrc-kubectl-alias:
    cmds:
    - wget -O ~/.kubectl_aliases https://raw.githubusercontent.com/ahmetb/kubectl-aliases/master/.kubectl_aliases
    - echo '[ -f ~/.kubectl_aliases ] && source ~/.kubectl_aliases' >> ~/.bashrc

  github-install-xh:
    cmds:
    - curl -sfL https://raw.githubusercontent.com/ducaale/xh/master/install.sh | sh
    
  upx-compress:
    cmds:
    - upx /usr/local/bin/*
    - upx ~/.arkade/bin/*
    
  clean-tmp:
    cmds:
    - rm -rf /tmp/*
    
  build:
    cmds:
    - task: oh-my-bash
    - task: bashrc-complete-alias
    - task: install-dingtalk
    - task: apt-install
    - task: arkade-install-helmfile
    - task: brew-install
    #- task: apt-install-fpm
    - task: upx-compress
    - chmod +x /usr/local/bin/* ~/.arkade/bin/*
    - task: clean-tmp

  default:
    cmds:
    - task: build
